### ISSUE TITLE
dotenv upstream is out of date

### ISSUE THREAD

**Issue by neybar** [mrsteele/dotenv-defaults#1]
I just found your module, and it is just what I needed!  -- Thanks

I noticed that you are depending on an out of date version of dotenv.  I checked out the repo thinking I could just do a quick version bump, but I'm not able to get tests to pass.  I think my system is struggling with babel and jest. 

[https://www.npmjs.com/package/dotenv](https://www.npmjs.com/package/dotenv)

**Comment by mrsteele** [comment]
Good observation @neybar, however the version bump from dotenv was only to remove support for previous versions of node.

Instead, I opted to just keep the current version for now as it is a breaking change and I do not want to subsequently remove support for everyone in lower node versions using this module.

You can read more about it here, and you will see it was primarily changes to the tests and node v4 features:
https://github.com/motdotla/dotenv/commit/d5ff527d3d64acb8ede665f3e64ae725db8af4e4

**Comment by mrsteele** [comment]
Closing due to lack of participation.

Feel free to reopen this if you can provide more details, thanks.
