### ISSUE TITLE
Use Snyk instead

### ISSUE THREAD

**Issue by mrsteele** [mrsteele/dotenv-defaults#19]
Greenkeeper looks like its gone. Would appreciate some help on this por favor.

**Comment by bennycode** [comment]
@mrsteele do you want to use Snyk for automated dependency updates? I can help you by replacing it with [Dependabot](https://dependabot.com/). It's a fantastic tool and got acquired by GitHub.

**Comment by mrsteele** [comment]
@bennyn I actually just integrated Dependebot. Thanks for you interest in this plugin!
