### ISSUE TITLE
I had a similar idea :-P

### ISSUE THREAD

**Issue by piranna** [mrsteele/dotenv-defaults#2]
At https://github.com/piranna/config I'm fetching config values from several places, one of them is dotenv... and the defaults are from package.json `config` object :-) Do you find it interesting to use it as a default value in addition to `.env.defaults` file? :-)

**Comment by mrsteele** [comment]
I guess that could be an option, but currently we put it in a separate file with the idea being that you could just copy/paste the contents into an actual `.env` file and it would have everything in the correct format.

**Comment by piranna** [comment]
isn't that similar to the `.env.sample`?

**Comment by mrsteele** [comment]
What is the context? I think sample is meant as a guide where defaults is meant as the base by which your env is set.

Regardless this module only references a default file, no sample.

On Sep 11, 2018, at 5:31 PM, Jesús Leganés-Combarro <notifications@github.com<mailto:notifications@github.com>> wrote:


isn't that similar to the .env.sample?

**Comment by piranna** [comment]
Sample is designed to copy and paste it literal and fill it with the correct data, while defaults I think should work standalone and just only need to add a `.env` with the fields that change, not need to copypaste it.

**Comment by mrsteele** [comment]
What you are taking about sounds like “dotenv-safe” although that gives you errors if you don’t use al fields.

On Sep 11, 2018, at 5:51 PM, Jesús Leganés-Combarro <notifications@github.com<mailto:notifications@github.com>> wrote:


Sample is designed to copy and paste it literal and fill it with the correct data, while defaults I think should work standalone and just only need to add a .env with the fields that change, not need to copypaste it.

**Comment by mrsteele** [comment]
Closing due to lack of participation.

Feel free to reopen this if you can provide more details, thanks.

**Comment by piranna** [comment]
I've found https://github.com/keithmorris/node-dotenv-extended has what I wanted :-)
